apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kitchen-producer-persistent-volume-claim
  labels:
    app: kitchen-producer
    tier: backend
  annotations:
    description: "Claim para acessar o volume persistente do microsserviço kitchen-producer"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
