apiVersion: v1
kind: PersistentVolume
metadata:
  name: kitchen-producer-persistent-volume
  labels:
    app: kitchen-producer
    tier: backend
  annotations:
    description: "Volume persistente para dados do microsserviço kitchen-producer"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /data/kitchen-producer/logs
