apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen-producer-deployment
  labels:
    app: kitchen-producer
    tier: backend
    environment: production
  annotations:
    description: "Microsserviço responsável por criar contatos"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kitchen-producer
  template:
    metadata:
      labels:
        app: kitchen-producer
        tier: backend
        environment: production
      annotations:
        description: "Pod do microsserviço kitchen-producer"
        redeploy-timestamp: "{{timestamp}}"
    spec:
      containers:
        - name: kitchen-producer
          image: acrfiap2025.azurecr.io/kitchen-producer:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: kitchen-producer-configmap
          volumeMounts:
            - name: kitchen-producer-volume
              mountPath: /app/logs/kitchen-producer
          readinessProbe:
            httpGet:
              path: /kitchen-producer/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /kitchen-producer/health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
      imagePullSecrets:
        - name: acr-kitchen-producer
      volumes:
        - name: kitchen-producer-volume
          persistentVolumeClaim:
            claimName: kitchen-producer-persistent-volume-claim